### ISSUE TITLE
Visual Studio 2017 version

### ISSUE THREAD

**Issue by Speedy37** [rxcompile/UE4Intellisense#3]
Can you publish a VS2017 version of this tool on the marketplace ?

**Comment by rxcompile** [comment]
Thanks to @FrostByteGER for his commit for supporting VS2017. I merged his commit to repo and rebuilded .vsix on AppVeyor.
Sadly, but version for VS2017 working extreamely slow, so that I decided not to publish it on the marketplace.
Sorry, but no plans on supporting this extension any more and making it run faster on VS2017, so you can grab new release from this repo or build this extension yourself.
